library(plyr)
library(dplyr)
library(reshape2)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip",destfile="./projectData.zip", method="curl")
unzip("projectData.zip")
features <- read.csv("./UCI HAR Dataset/features.txt", header=F, sep=" ", stringsAsFactors=F)
features <- features[,2]
x_test <- read.csv("./UCI HAR Dataset/test/X_test.txt", sep="", header=F)
y_test <- read.csv("./UCI HAR Dataset/test/y_test.txt", sep="", header=F)
subject_test <- read.csv("./UCI HAR Dataset/test/subject_test.txt", sep="", header=F)
x_train <- read.csv("./UCI HAR Dataset/train/X_train.txt", sep="", header=F)
y_train <- read.csv("./UCI HAR Dataset/train/y_train.txt", sep="", header=F)
subject_train <- read.csv("./UCI HAR Dataset/train/subject_train.txt", sep="", header=F)
test_combined <- cbind(subject_test, y_test, x_test)
train_combined <- cbind(subject_train, y_train, x_train)
df <- rbind(test_combined, train_combined)
names(df) <- c("subject", "activity",features)
df <- df[,grepl("mean\\(\\)|std\\(\\)|subject|activity",names(df))]
df <- arrange(df, subject, activity)
df <- melt(df, id=c("subject","activity"),measure.vars=3:68)
dfAverages <- dcast(df, subject + activity ~ variable, mean)
dfAverages$activity <- mapvalues(dfAverages$activity, from=(1:6), to=c("walking","walking_upstairs","walking_downstairs","sitting","standing","laying"))
View(dfAverages)
